DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS job;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT, 
    username TEXT UNIQUE NOT NULL, 
    password TEXT NOT NULL
);

CREATE TABLE job (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id INTEGER NOT NULL, 
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    job_title TEXT NOT NULL, 
    job_desc TEXT NOT NULL, 
    FOREIGN KEY (author_id) REFERENCES user (id)
);